### ISSUE TITLE
C# Kernel

### ISSUE THREAD

**Issue by dhirschfeld** [Microsoft/jupyter-core#16]
This project looks very interesting! In particular I'm pretty interested in a kernel for C# and so am curious if there are any plans to build that?

The existing [`icsharp`](https://github.com/zabirauf/icsharp) kernel seems to be demo quality and mostly abandoned.

**Comment by cgranade** [comment]
@dhirschfeld: I don't think we have any plans at the moment, but that's a great suggestion. Helping out with icsharp and scriptcs could potentially be a wonderful use for jupyter-core!

**Comment by dhirschfeld** [comment]
Thanks for the info @cgranade! I'll close this so as to not clutter the issues. If anything changes it can always be reopened...

**Comment by cgranade** [comment]
Thanks for the suggestion, @dhirschfeld! Taking a quick look at scriptcs, I think it will be challenging to get a C# kernel that works on .NET Core with that, but the scriptcs devs suggested looking at the `dotnet-script` project instead, as that supports .NET Core out of the box. Maybe https://github.com/filipw/dotnet-script/blob/c294533dedbba05cde2fe9e86e5560ce18ae02b1/src/Dotnet.Script.Core/Interactive/InteractiveRunner.cs would be a good place to start?

**Comment by Oceania2018** [comment]
@cgranade Please consider about [ICSharpCore](https://github.com/SciSharp/ICSharpCore), It's a .net core kernel running with `Jupyter`.
