### ISSUE TITLE
Very similar with SciSharp ICSharpCore

### ISSUE THREAD

**Issue by Oceania2018** [microsoft/jupyter-core#17]
Hi,
Great to see the new Jupyter kernel. This is very similar with [ICSharpCore](https://github.com/SciSharp/ICSharpCore). I will take a look at it, and plan to retire my project due to lack of resource. and might contribute to this project to work with my other ML libraries.

**Comment by Oceania2018** [comment]
Hmm, it seems doesn't support C# engine yet?

**Comment by cgranade** [comment]
Thanks for pointing us out to ICSharpCore, looks like an interesting approach! As for a C# engine, we haven't made one yet, no. That said, we recently gotten a feature request to do so (#16), such that adding a C# engine would be a really lovely contribution!

**Comment by Oceania2018** [comment]
I'll PR about C# engine. @cgranade

**Comment by cgranade** [comment]
@Oceania2018: I took a quick stab at using dotnet-script on the https://github.com/Microsoft/jupyter-core/tree/cgranade/csharp-example branch if you're interested, but I ran into a slight trouble in that the current behavior of dotnet-script is to always `Print` the return value of a REPL call.

**Comment by Oceania2018** [comment]
Don't want REPL call?

**Comment by Oceania2018** [comment]
@cgranade Check our new example: https://github.com/SciSharp/ICSharpCore/issues/2

**Comment by rmshaffer** [comment]
Closing this as we don't plan to add language-specific kernels to this project. Other projects should feel free to consume this and build on top of it! For example, a Q# kernel using jupyter-core is available at https://github.com/microsoft/iqsharp. Additionally, Jupyter kernels for .NET languages such as C# and F# are now available at https://github.com/dotnet/interactive.
