### ISSUE TITLE
Execution count not incrementing in nteract web client

### ISSUE THREAD

**Issue by cgranade** [microsoft/jupyter-core#35]
When using Microsoft.Jupyter.Core-based kernels from within the nteract web client, the execution count is not correctly incremented after executing each cell. Thanks to @captainsafia for the report!

**Comment by captainsafia** [comment]
Doing some GitHub notifications triage and came across this!

Are you still able to reproduce this on the latest version of nteract (not available on binder yet, you'll have to use the master branch of the nteract/nteract repo).

It might have something to do with https://github.com/nteract/nteract/issues/4541.
