### ISSUE TITLE
IEcho install instructions in README.md are incorrect.

### ISSUE THREAD

**Issue by ISimplifyComplexity** [microsoft/jupyter-core#36]
Is this failing because I just installed .NET Core 3? 

`PS C:\Windows\system32> dotnet iecho install`

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-iecho does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
PS C:\Windows\system32> dotnet tool install -g Microsoft.Jupyter.Example.IEcho
error NU1101: Unable to find package microsoft.jupyter.example.iecho. No packages exist with this id in source(s): C:\Program Files\dotnet\sdk\NuGetFallbackFolder, Microsoft Visual Studio Offline Packages, nuget.org
The tool package could not be restored.
Tool 'microsoft.jupyter.example.iecho' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by cgranade** [comment]
@KiransHub: Thanks for the report, it looks like this comes down to a mistake we've made with the installation instructions for the IEcho example. Namely, we don't currently publish a NuGet package for the IEcho example, such that only installing from the local build is supported. I've changed the title of this bug to reflect that we need to update the README accordingly. Thanks again for letting us know!
