### ISSUE TITLE
Can't install kernel if user's home directory has spaces 

### ISSUE THREAD

**Issue by anpaz-msft** [microsoft/jupyter-core#39]
As reported on https://github.com/microsoft/iqsharp/issues/63

## Describe the bug
When there are spaces in the user's home directory iqsharp cannot be installed, giving errors like the ones shown in this ticket:

MicrosoftDocs/quantum-docs-pr#617

I reproduced the error on a Windows 10 machine, with a user with spaces in the name.

## To Reproduce

Create a user with spaces in the name
Follow the steps here to install the QDK for either the python or jupyter use-case: https://docs.microsoft.com/en-us/quantum/install-guide/?view=qsharp-preview
Expected behavior
IQ sharp installed correctly.

## System information

OS: Windows
Browser N/A
Version
Windows 10
Python 3.8
QDK 0.10

**Comment by rmshaffer** [comment]
Tested and verified that this works in current builds, presumably fixed by #40. Closing.
