### ISSUE TITLE
'No such file or directory' when trying to install a kernel if jupyter is missing.

### ISSUE THREAD

**Issue by anpaz-msft** [microsoft/jupyter-core#8]
I tried to install iqsharp on an environment that didn't have Jupyter yet, and just got this error:
```
(base) anpaz-imac:~/ $ dotnet iqsharp  install
No such file or directory
```
We should give more hints about what is going on or maybe even check if Jupyter is installed.

**Comment by cgranade** [comment]
This should now be resolved by #31.
